# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 大数据商务智能(BI)专栏
subtitle: '专注 系统 专业 '
description: '大数据商务智能(BI)方案设计'
keywords: 商务智能 数据仓库 实时计算
author: 易向东
language: zh-CN
timezone: Asia/Shanghai

leancloud_counter_security:
  enable_sync: true
  app_id: R5lCdvURWRYwXoHUGjSiPegb-gzGzoHsz
  app_key: GtuKVuaKr00gVSlupac0Ejf8

# URL
# :year/:month/:day/
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://etop.work
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
  
baidu_url_submit:
  count: 50               # 提交最新的多少个链接
  host: etop.work   # 在百度站长平台中添加的域名
  token: C9vt8oFiJ71OYTGY      # 秘钥
  path: baidu_urls.txt   # 文本文档的地址， 新链接会保存在此文本文档里
#baidu_push: true

# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'  
    
algolia:
   applicationID: '9133ZNYPST'
   apiKey: '438b8e1d3359f650966c28b8caf83dea'
   adminApiKey: '590ed055e8cab685b998d9d4461559ce'
   indexName: 'yixiangdong_index'
   chunkSize: 5000
   fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title
    
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
favicon: css/images/favicon.ico


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
categories: 
- 大数据BigData
tag_map:
tags:
- 数据仓库
- Flink实时计算
- 用户画像
- ML
- sparkstreaming
- 源码分析
- ClickHouse
# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false
thumbnail: true

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# 看板娘动态模型插件

## https://github.com/JoeyBling/live2d-widget.js
#live2d:
  # (关闭请设置为false)
#  enable: true
  # 模型名称(取值请参考：https://github.com/JoeyBling/hexo-theme-yilia-plus/wiki/live2d%E6%A8%A1%E5%9E%8B%E5%8C%85%E5%B1%95%E7%A4%BA)
#  model: wanko
#  bottom: -30
  #display:
  #  position: right # 显示位置：left/right(default: 'right')
  #  width: 145  # 模型的长度(default: 150)
  #  height: 315 # 模型的高度(default: 300)
  #  hOffset: 50 # 水平偏移(default: 0)
    #vOffset: -20 # 垂直偏移(default: -20)
  #mobile:
  #  show: true # 是否在移动设备上显示(default: true)
  # scale: 0.6 # 移动设备上的缩放(default: 0.5)
  #react:
  #  opacity: 0.8 # 模型透明度(default: 0.7)


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
#  type: ''
deploy:
- type: git
  repo: 
    github: git@github.com:yixiangdong/yixiangdong.github.io.git
    coding: git@e.coding.net:yixiangdong/yixiangdong.coding.net.git
  branch: master
- type: baidu_url_submitter